---
users:
  - groups: "cloudadmins"
    username: user100
    state: present
    public_key_path: /home/user100

  - groups: "cloudadmins"
    username: user200
    state: present
    public_key_path: /home/user200

  - groups: "cloudadmins"
    username: user300
    state: present
    public_key_path: /home/user300

sudoersUpdate:
  - path: /etc/sudoers.d/nopasswd
    validate: /usr/sbin/visudo -cf %s
    state: present
